image:
  name: django-mobans-lint-image
  version: 0.1
  maintainer: jayvdb@gmail.com
  parent: opensuse/tumbleweed
  python_version: 3.7
  node_version: 10
  zypper:
    sources:
      - devel:languages:python
      - home:jayvdb:coala
    packages:
      - coala
      - nltk-data-averaged_perceptron_tagger
      - nltk-data-punkt
      - python3-coala-bears
      - python3-autoflake
      - python3-autopep8
      - python3-eradicate
      - python3-git-url-parse
      - python3-nltk
      - python3-pyflakes
      - python3-yamllint
      - git-core  # for git bears
      - ShellCheck
  npm:
    - dockerfile_lint
  run:
    cmd: coala --ci
  omit:
    expose: true

#requires:
  # ../docker-mobans

configuration:
  configuration: .moban.yaml
  template_dir:
    - ../docker-mobans/.moban.dt/
targets:
  - Dockerfile: Dockerfile.jj2
  - .dockerfile_lint_rules.yaml: dockerfile_lint_rules.yaml.jj2
  - .gitlab-ci.yml: gitlab-ci.yml.jj2
  - .travis.yml: travis.yml.jj2
copy:
  - .coafile: .coafile
  - .gitignore: .gitignore
  - hooks/build: hooks/build
