sudo: false
dist: xenial
language: generic
services: docker

env:
  global:
    - IMAGE_NAME=django-mobans-lint-image:this

before_script:
  - docker run -v=$(pwd):/app --workdir=/app djangomobans/lint-image

script:
  - hooks/build
  - docker images
  # Re-run lint using built image
  - docker run -v=$(pwd):/app --workdir=/app $IMAGE_NAME

notifications:
  email: false
